User/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from User.views import UserPageView, SuccessLoginView, SuccessSignUpView, SuccessLogoutView, HomePageView
# from django.contrib.auth import
from . import views
urlpatterns = [
	url(r'^$', HomePageView.as_view(), name='home_view'),
    url(r'^users', UserPageView.as_view(), name='user_list'),
    url(r'^success-signup', SuccessSignUpView.as_view(), name='success-signup'),
    url(r'^success-loguin', SuccessLoginView.as_view(), name='success-loguin'),
    url(r'^success-logout', SuccessLogoutView.as_view(), name='success-logout'),
    url(r'^login/$', views.authentication, name='authentication'),
    url(r'^create', views.create_data, name='create_data'),
    url(r'^signup', UserPageView.as_view(), name='signup'),
    url(r'^home', HomePageView.as_view(), name='home_view'),
    
]

app/app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('User.urls', namespace='user')),
]
# No se que hace esto
 # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('User.urls', namespace='user')),
    url(r'', include('cms.urls', namespace='cms')),
]
# No se que hace esto
 # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from cms.views import TeamListView
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    url(r'^teams/$',TeamListView.as_view(),name='team_list'),
	]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
# from django.contrib.auth.models import AbstractBaseUser
# from django.contrib.auth.models import BaseUserManager
# from django.contrib.auth.models import PermissionsMixin
# from django.core.mail import send_mail
from django.db import models

class UserData(models.Model):

    username = models.CharField(
        unique=True,
        verbose_name='Nombre de usuario',
        max_length=100,
    )

    user_password = models.CharField(
        unique=True,
        verbose_name='Password de usuario',
        max_length=100,
    )
# class UserDataComplete(models.Model):

    REQUIRED_FIELDS = [
        'first_name',
        'last_name',
        'document_type',
        'document_number',
    ]

    DOCUMENT_CHOICES = (
        (10, 'Cedula de ciudadanía'),
        (20, 'Cedula de extranjería'),
        (30, 'Pasaporte'),
    )

    GENRE_CHOICES = (
        (10, 'Masculino'),
        (20, 'Femenino'),
        (30, 'Otro'),
    )

    email = models.EmailField(
        unique=True,
        verbose_name='Correo electrónico',
    )

    first_name = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Nombres',
    )

    last_name = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Apellidos',
    )

    document_type = models.PositiveSmallIntegerField(
        choices=DOCUMENT_CHOICES,
        verbose_name='Tipo de documento',
    )

    document_number = models.CharField(
        max_length=64,
        verbose_name='Número de documento',
    )

    document_expedition = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Lugar de expedición',
    )

    nationality = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Nacionalidad',
    )

    birth_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='Fecha de nacimiento',
    )

    department = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Departamento',
    )

    city = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Ciudad',
    )

    address = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        verbose_name='Dirección',
    )

    mobile_phone = models.CharField(
        blank=True,
        null=True,
        max_length=64,
        verbose_name='Teléfono Celular',
    )

    genre = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        choices=GENRE_CHOICES,
        verbose_name='Genero',
    )

    date_joined = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha de registro',
    )


    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

    # def email_user(self, subject, message, from_email=None, **kwargs):
    #     send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = 'usuario'
        verbose_name_plural = 'usuarios'
        unique_together = ('document_type', 'document_number')
        ordering = ('first_name', 'last_name')

User/forms.py
from django import forms
from User.models import UserData

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = UserData
        fields = "__all__"

    # def __init__(self, *args, **kwargs):
    #     super(RegistrationForm, self).__init__(*args, **kwargs)

    #     cleaned_data = super(RegistrationForm, self).clean()

    #     return cleaned_data

User/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from User.forms import RegistrationForm
from User.models import UserData
from .mixins import LoginRequiredMixin



def authentication(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        if action == 'signup':
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return redirect('/success-signup')

        elif action == 'login':
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('/success-loguin')

        elif action == 'logout':
            print 'hellow mtf'
            logout(request)
            return redirect('/success-logout')

    return render(request, 'login.html', {})

def create_data(request):
    if request.method == 'POST':
        myForm = RegistrationForm(request.POST)
        if myForm.is_valid():
            myForm.save()
            return redirect('/success-loguin')
    else:
        myForm = RegistrationForm()

    return render(request, 'user_form.html', {'myForm': myForm})

class UserPageView(ListView):
    model = UserData
    template_name = "user_list.html"

    def get_queryset(self):
        return User.objects.all()

class HomePageView(ListView):
    model = UserData
    template_name = "home.html"

class SuccessLoginView(LoginRequiredMixin, TemplateView):
    model = UserData
    template_name = "success_login.html"

    def get_queryset(self):
        return UserData.objects.all()

class SuccessSignUpView(TemplateView):
    template_name = "success_sign_up.html"

class SuccessLogoutView(TemplateView):
    template_name = "success_logout.html"

User/templates/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
  </head>
<body>
<div class="container-fluid">
  <header id="headerHome" class="header-home-open row">
    <div class="logo col-xs-9 col-md-3 col-lg-4">
      <img class="logo-image col-xs-offset-2 col-lg-offset-3 " src="{% static 'img/logo.jpg' %}" alt="El unico grande">
    </div>    
    <div id="btnMenu" class="button-menu col-xs-3">
      <a class="button-menu-img"><img src="{% static 'img/boton_menu.png' %}"></a>
    </div>
    <nav class="nav col-md-9 col-lg-8">
      <ul>
        <li>
          <a class="item" href="{% url 'user:home_view' %}">Home</a>    
        </li> 
        <li>
          <a class="item" href="{% url 'user:user_list' %}">Users</a>    
        </li>
        <li>
          <a class="item" href="{% url 'cms:team_list' %}">Pictures</a>  
        </li>
        <li>
          <a class="item" href="{% url 'user:authentication' %}">Access to Intranet</a>   
        </li>  
        <li>
          <a class="item" href="{% url 'admin:index' %}">Access to Admin</a>    
        </li>  
      </ul>
    </nav>
  </header>
  <div id="buttonlistclass" class="button-list-hidden container-menu">
        <ul class="ul-list">
          <li>
            <a class="item" href="{% url 'user:home_view' %}">Home</a>    
          </li> 
          <li>
            <a class="item" href="{% url 'user:user_list' %}">Users</a>    
          </li>
          <li>
            <a class="item" href="{% url 'cms:team_list' %}">Pictures</a>  
          </li>
          <li>
            <a class="item" href="{% url 'user:authentication' %}">Access to Intranet</a>
          </li>  
          <li>
            <a class="item" href="{% url 'admin:index' %}">Access to Admin</a>    
          </li>  
        </ul>
      </div> 
</div>
  <button id="btnMenu2" class="button-main-home">Menu</button>
  {% block login_content %}
  {% endblock %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.min.js"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/bundle.js' %}"></script>
  <script type="text/javascript">
    (function() {
      var mainPanel = document.getElementById('btnMenu2');
      var sidePanel = document.getElementById('headerHome');
      var sidePanel2 = document.getElementById('buttonlistclass');
      var hammerPanel = new Hammer(mainPanel);
      var hammerSide = new Hammer(sidePanel);
      mainPanel.addEventListener('click', onSwipe)
      function onSwipe() {
        sidePanel.classList.toggle('header-home-open');
        sidePanel2.classList.remove('button-list');
      }
      function onClick() {
        sidePanel.classList.toggle('header-home-open');
        sidePanel2.classList.remove('button-list');
      }      
    }());
  </script>
</body>
<footer>
    <h4>c2media</h4>
</footer>
</html>

User/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <title>{% block title %}{% endblock title %}</title>
    <!-- smoosh -->
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- endsmoosh -->
    <!-- smoosh -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- endsmoosh -->
    <!-- smoosh -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <!-- endsmoosh -->
  </head>
<body>

<div class="container-fluid">

  <header class="row">
    <div class="logo col-lg-2">
        
        <img class="logo-image col-lg-offset-3 " src="{% static 'img/logo.jpg' %}" alt="El unico grande">

      </div>
    <nav class="col-lg-10">
      <ul class="col-lg-offset-3">
        <li>
          <a class="item" href="#">Home</a>    
        </li> 
        <li>
          <a class="item" href="{% url 'user:user_list' %}">Users</a>    
        </li>
        <li>
          <a class="item" href="{% url 'cms:team_list' %}">Pictures</a>  
        </li>
        <li>
          <a class="item" href="{% url 'user:authentication' %}">Access to Intranet</a>   
        </li>  
        <li>
          <a class="item" href="#">Access to Admin</a>    
        </li>  
         
      </ul>
    </nav>
  </header>
</div>

  {% block login_content %} {% endblock %}

  <!-- smoosh -->
  <script src="{% static 'js/bundle.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- endsmoosh -->
</body>

<footer>
    <h4>c2media</h4>

</footer>

</html>

User/templates/login.html
{% extends 'index.html' %}
{% block title %}
Login
{% endblock title %}
{% block login_content %}
<div class="container-main">
  <div class="container">
    <div class="row container-login center-block">
      {% if user.is_authenticated %}
        <h2>Logout</h2>
        <form action="" method="post">
          {% csrf_token %}
          <input type="hidden" name="action" value="logout">
          <button class="btn btn-primary" type="submit">Logout</button>          
        </form>
      {% else %}
        <form action="" method="post">
          {% csrf_token %}
          <input type="hidden" name="action" value="login">
          <input type="text" name="username">
          <input type="password" name="password">
          <button type="submit" class="btn btn-primary">Login</button>
          <a href="#"><button type="button" class="btn btn-primary">Signup</button></a>
        </form>        
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

User/templates/signup.html
{% extends index.html %}
<h2>signup</h2>
<form action="" method="post">
	{% csrf_token %}
    <input type="hidden" name="action" value="signup">
    <input type="text" name="username">
    <input type="text" name="password">
    <button type="submit">signup</button>
</form>

User/templates/success_login.html
{% extends 'index.html' %}
{% block login_content %}
    {% if user.is_authenticated %}
        <p>
           Bienvenido {{ user.username }}, puedes ir a <a href="{% url 'user:create_data' %}">completar datos</a>
        </p>
    {% else %}
        <p>
           El usuario se creó correctmanete, <a href="{% url 'user:authentication' %}">loguearme</a>
        </p>
    {% endif %}
        <p>Ir donde mi padre
            <a href="http://www.atlnacional.com.co/">GO</a>
        </p>
{% endblock %}

User/templates/success_logout.html
{% extends 'index.html' %}
{% block login_content %}
<p>
    Cerró sesión correctamente
</p>
<p>
	volver al <a href="{% url 'user:user_list' %}">home</a>
</p>
{% endblock %}

User/templates/success_sign_up.html
{% extends 'index.html' %}
{% block login_content %}
    {% if user.is_authenticated %}
        <p>
        	<a href="{% url 'user:create_data' %}">Completar datos</a>
        </p>
    {% else %}
        <p>
            Felicidades, el Usuario se creó correctamente.
        </p>
        <a href="{% url 'user:authentication' %}">Loguearme</a>
    {% endif %}
{% endblock %}

User/templates/user_form.html
{% extends 'index.html' %}
{% block login_content %}

{% if user.is_authenticated %}
    <form action='/create/' method='post'>
        {% csrf_token %}
        {{ myForm.as_p  }}
        <button type='submit'>Eviar</button>
    </form>
{% else %}
    <p>Debes loguearte para poder registrar datos.
    </p>
    <a href="{% url 'user:authentication' %}">Loguearme</a>
{% endif %}
{% endblock %}

User/templates/user_list.html
{% extends 'index.html' %}
{% block title %}
Users
{% endblock title %}
{% block login_content %}      
<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover">                
                <h5>USUARIOS</h5>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>State</th>
                        <th>Autenticate</th>
                    </tr>
                </thead>
                {% for data in object_list %}
                <tbody>
                    <tr>
                        <td>{{ data.first_name }}
                            {{ data.username }}
                        </td>
                        <td>{{ data.email }}</td>
                        <td>{{ data.is_active }}</td>
                        <td>{{ data.is_authenticated }}</td>
                    </tr>
                </tbody>
                {% endfor %}                  
            </table>
        </div>
    </div>      
</div>        
{% endblock %}